[pytest]
testpaths = tests
norecursedirs =
    .git
    .hg
    .nox
    .tox
    .venv
    __pycache__
    audits
    build
    dist
    env
    node_modules
    pages-dist
    public
    venv
addopts = --ignore=audits
