#!/usr/bin/env python3
"""Apply only high-confidence conservation hunt-code/boundary corrections.

Inputs are generated by the candidate audit. Rows are applied only when the
candidate file marks them as safe, meaning DATABASE.csv supplied one clear
species + sex + weapon + hunt-name match.
"""

from __future__ import annotations

import csv
import shutil
from datetime import datetime, timezone
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
CANDIDATES = (
    ROOT
    / "audits"
    / "2025_canonical_finalization"
    / "conservation_real_code_species_weapon_candidate_replacements.csv"
)
DATABASE = ROOT / "pipeline" / "RAW" / "hunt_unit_database" / "2026" / "csv" / "DATABASE.csv"
BACKUP_DIR = ROOT / "audits" / "2025_canonical_finalization" / "backups"
AUDIT = (
    ROOT
    / "audits"
    / "2025_canonical_finalization"
    / "conservation_safe_code_boundary_apply_audit.csv"
)


def clean(value: object) -> str:
    if value is None:
        return ""
    return " ".join(str(value).split())


def load_database() -> dict[str, dict[str, str]]:
    with DATABASE.open(newline="", encoding="utf-8-sig") as handle:
        return {row["hunt_code"].upper(): row for row in csv.DictReader(handle)}


def load_safe_rows() -> list[dict[str, str]]:
    with CANDIDATES.open(newline="", encoding="utf-8") as handle:
        return [row for row in csv.DictReader(handle) if row.get("apply_safe") == "True"]


def header_index(sheet) -> dict[str, int]:
    return {clean(cell.value).upper(): idx for idx, cell in enumerate(sheet[1], start=1)}


def write_if_present(sheet, columns: dict[str, int], row_idx: int, header: str, value: str) -> None:
    col = columns.get(header.upper())
    if col:
        sheet.cell(row=row_idx, column=col).value = value


def main() -> int:
    database = load_database()
    safe_rows = load_safe_rows()
    rows_by_workbook: dict[Path, list[dict[str, str]]] = {}
    for row in safe_rows:
        rows_by_workbook.setdefault(ROOT / row["workbook"], []).append(row)

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    audit_rows: list[dict[str, str]] = []

    for workbook_path, candidate_rows in rows_by_workbook.items():
        backup_path = (
            BACKUP_DIR
            / f"{workbook_path.stem}.before_safe_code_boundary_apply_{timestamp}{workbook_path.suffix}"
        )
        shutil.copy2(workbook_path, backup_path)

        workbook = openpyxl.load_workbook(workbook_path)
        sheet = workbook[workbook.sheetnames[0]]
        columns = header_index(sheet)

        for candidate in candidate_rows:
            row_idx = int(candidate["row"])
            new_code = clean(candidate["best_code"]).upper()
            database_row = database[new_code]

            old_code = clean(sheet.cell(row=row_idx, column=columns["HUNT CODE"]).value).upper()
            old_boundary = clean(sheet.cell(row=row_idx, column=columns.get("BOUNDARY ID", 0)).value)
            old_hunt_name = clean(sheet.cell(row=row_idx, column=columns.get("HUNT NAME", 0)).value)

            write_if_present(sheet, columns, row_idx, "HUNT CODE", database_row["hunt_code"])
            write_if_present(sheet, columns, row_idx, "CONSERVATION_CODE", f"C_{database_row['hunt_code']}")
            write_if_present(sheet, columns, row_idx, "BOUNDARY ID", database_row["boundary_id"])
            write_if_present(
                sheet,
                columns,
                row_idx,
                "MAP GEOJSON",
                f"processed_data/boundaries/{database_row['hunt_code']}.geojson",
            )
            write_if_present(sheet, columns, row_idx, "MAP STATUS", "database_safe_corrected")
            write_if_present(sheet, columns, row_idx, "SPECIES", database_row["species"])
            write_if_present(sheet, columns, row_idx, "SEX", database_row["sex_type"])
            write_if_present(sheet, columns, row_idx, "SEX TYPE", database_row["sex_type"])
            write_if_present(sheet, columns, row_idx, "WEAPON", database_row["weapon"])
            write_if_present(sheet, columns, row_idx, "HUNT NAME", database_row["hunt_name"])

            audit_rows.append(
                {
                    "workbook": str(workbook_path.relative_to(ROOT)).replace("\\", "/"),
                    "sheet": sheet.title,
                    "row": str(row_idx),
                    "old_hunt_code": old_code,
                    "new_hunt_code": database_row["hunt_code"],
                    "old_boundary_id": old_boundary,
                    "new_boundary_id": database_row["boundary_id"],
                    "old_hunt_name": old_hunt_name,
                    "new_hunt_name": database_row["hunt_name"],
                    "source": "DATABASE.csv",
                    "backup_path": str(backup_path.relative_to(ROOT)).replace("\\", "/"),
                }
            )

        workbook.save(workbook_path)

    AUDIT.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "workbook",
        "sheet",
        "row",
        "old_hunt_code",
        "new_hunt_code",
        "old_boundary_id",
        "new_boundary_id",
        "old_hunt_name",
        "new_hunt_name",
        "source",
        "backup_path",
    ]
    with AUDIT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(audit_rows)

    print(f"applied={len(audit_rows)}")
    print(f"audit={AUDIT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
