"""Add 2026 hunt-code prefix normalization metadata to finalized truth files.

This preserves the raw/current hunt_code value. It only adds comparable prefix
metadata for model routing and cross-year audits.
"""

from __future__ import annotations

import csv
import json
import os
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGETS = [
    ROOT / "data_truth" / "finalized_point_distribution.csv",
    ROOT / "data_truth" / "finalized_hunt_truth.csv",
]
CROSSWALK = (
    ROOT
    / "data_truth"
    / "crosswalk_truth"
    / "normalized"
    / "current_to_historical_hunt_code_crosswalk_2026.csv"
)
OUT_DIR = ROOT / "audits" / "2026_hunt_code_prefix_crosswalk"
DETAIL = OUT_DIR / "2026_prefix_crosswalk_detail.csv"
SUMMARY = OUT_DIR / "2026_prefix_crosswalk_summary.csv"
STATUS = OUT_DIR / "2026_prefix_crosswalk_status.json"

NEW_COLUMNS = [
    "legacy_hunt_code_prefix",
    "hunt_code_prefix_status",
]

PROTECTED_VALUE_COLUMNS = {
    "applicants",
    "permits",
    "applicants_total",
    "permits_bonus",
    "permits_regular",
    "permits_total",
    "success_rate",
}

# These are family/report labels generated by the 2026 UtahDraws-style extracts,
# not unique hunt codes. They need a comparable old-style family prefix, but
# should not be rewritten into fake hunt codes like "BI" or "EB".
FAMILY_LABEL_PREFIX = {
    "BER": "BR",
    "BIS": "BI",
    "BPU": "BR",
    "DBS": "DS",
    "DEE": "DB",
    "DHL": "DB",
    "ELK": "EB",
    "GDR": "DB",
    "GOA": "GO",
    "MOO": "MB",
    "PRO": "PB",
    "RMB": "RS",
}


def clean(value: object) -> str:
    return "" if value is None else str(value).strip()


def norm_year(value: object) -> str:
    text = clean(value)
    return text[:-2] if text.endswith(".0") else text


def alpha_prefix(code: str) -> str:
    match = re.match(r"^([A-Z]+)", clean(code).upper())
    return match.group(1) if match else ""


def read_crosswalk() -> dict[str, tuple[str, str, str]]:
    """Return current_code -> (historical_code, historical_prefix, status)."""
    if not CROSSWALK.exists():
        return {}
    result: dict[str, tuple[str, str, str]] = {}
    with CROSSWALK.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            current = clean(row.get("current_hunt_code")).upper()
            historical = clean(row.get("historical_hunt_code")).upper()
            historical_prefix = clean(row.get("historical_prefix")).upper()
            relationship = clean(row.get("relationship_type"))
            confidence = clean(row.get("mapping_confidence"))
            if not current:
                continue
            if historical_prefix:
                result[current] = (
                    historical,
                    historical_prefix,
                    f"CURRENT_2026_CODE_CROSSWALKED_TO_HISTORICAL_PREFIX:{relationship}:{confidence}",
                )
    return result


def prefix_metadata(row: dict[str, str], crosswalk: dict[str, tuple[str, str, str]]) -> tuple[str, str]:
    year = norm_year(row.get("year") or row.get("source_year") or row.get("actual_draw_year"))
    model_year = norm_year(row.get("model_year") or row.get("permit_year") or row.get("model_target_year"))
    code = clean(row.get("hunt_code")).upper()
    prefix = alpha_prefix(code)

    if not code:
        return "", "MISSING_HUNT_CODE"

    if year == "2026" or model_year == "2027":
        if code in FAMILY_LABEL_PREFIX:
            return FAMILY_LABEL_PREFIX[code], "FAMILY_AGGREGATE_LABEL_NOT_UNIQUE_HUNT_CODE"
        if code in crosswalk:
            _, historical_prefix, status = crosswalk[code]
            return historical_prefix or prefix[:2], status
        return prefix[:2], "UNCHANGED_2026_LEGACY_PREFIX"

    return prefix[:2], "UNCHANGED_HISTORICAL_PREFIX"


def row_signature(row: dict[str, str], fields: list[str]) -> tuple[str, ...]:
    return tuple(clean(row.get(field)) for field in fields if field in PROTECTED_VALUE_COLUMNS)


def rewrite_file(path: Path, crosswalk: dict[str, tuple[str, str, str]]) -> dict[str, object]:
    before_rows = 0
    after_rows = 0
    protected_fields: list[str] = []
    changed_prefix_rows = 0
    detail_rows: list[dict[str, str]] = []
    status_counts: Counter[str] = Counter()
    legacy_prefix_counts: Counter[str] = Counter()

    tmp = path.with_suffix(path.suffix + ".tmp_prefix_crosswalk")
    with path.open("r", encoding="utf-8-sig", newline="") as source:
        reader = csv.DictReader(source)
        if not reader.fieldnames:
            raise RuntimeError(f"{path} has no header")
        fields = list(reader.fieldnames)
        protected_fields = [field for field in fields if field in PROTECTED_VALUE_COLUMNS]
        for col in NEW_COLUMNS:
            if col not in fields:
                fields.append(col)

        with tmp.open("w", encoding="utf-8", newline="") as target:
            writer = csv.DictWriter(target, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            for row in reader:
                before_rows += 1
                before_signature = row_signature(row, protected_fields)
                old_prefix = clean(row.get("legacy_hunt_code_prefix"))
                old_status = clean(row.get("hunt_code_prefix_status"))
                legacy_prefix, status = prefix_metadata(row, crosswalk)
                row["legacy_hunt_code_prefix"] = legacy_prefix
                row["hunt_code_prefix_status"] = status
                after_signature = row_signature(row, protected_fields)
                if before_signature != after_signature:
                    raise RuntimeError(f"Protected value changed while processing {path}: row {before_rows}")

                if old_prefix != legacy_prefix or old_status != status:
                    changed_prefix_rows += 1

                year = norm_year(row.get("year") or row.get("source_year") or row.get("actual_draw_year"))
                model_year = norm_year(row.get("model_year") or row.get("permit_year") or row.get("model_target_year"))
                if year == "2026" or model_year == "2027":
                    status_counts[status] += 1
                    legacy_prefix_counts[legacy_prefix] += 1
                    if status != "UNCHANGED_2026_LEGACY_PREFIX":
                        detail_rows.append(
                            {
                                "dataset": str(path.relative_to(ROOT)),
                                "year": year,
                                "model_year": model_year,
                                "hunt_code": clean(row.get("hunt_code")).upper(),
                                "legacy_hunt_code_prefix": legacy_prefix,
                                "hunt_code_prefix_status": status,
                                "hunt_name": clean(row.get("hunt_name")),
                                "residency": clean(row.get("residency")),
                                "point_level": clean(row.get("point_level")),
                                "source_file": clean(row.get("source_file")),
                                "source_namespace": clean(row.get("source_namespace")),
                            }
                        )

                writer.writerow(row)
                after_rows += 1

    os.replace(tmp, path)
    return {
        "path": str(path.relative_to(ROOT)),
        "rows_before": before_rows,
        "rows_after": after_rows,
        "row_count_preserved": before_rows == after_rows,
        "changed_prefix_metadata_rows": changed_prefix_rows,
        "status_counts": dict(sorted(status_counts.items())),
        "legacy_prefix_counts": dict(sorted(legacy_prefix_counts.items())),
        "detail_rows": detail_rows,
    }


def write_csv(path: Path, rows: list[dict[str, object]], fields: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    crosswalk = read_crosswalk()
    results = [rewrite_file(path, crosswalk) for path in TARGETS]

    detail_rows: list[dict[str, str]] = []
    summary_rows: list[dict[str, object]] = []
    for result in results:
        detail_rows.extend(result.pop("detail_rows"))  # type: ignore[arg-type]
        for status, count in dict(result["status_counts"]).items():  # type: ignore[index]
            summary_rows.append(
                {
                    "dataset": result["path"],
                    "summary_type": "hunt_code_prefix_status",
                    "value": status,
                    "row_count": count,
                }
            )
        for prefix, count in dict(result["legacy_prefix_counts"]).items():  # type: ignore[index]
            summary_rows.append(
                {
                    "dataset": result["path"],
                    "summary_type": "legacy_hunt_code_prefix",
                    "value": prefix,
                    "row_count": count,
                }
            )

    write_csv(
        DETAIL,
        detail_rows,
        [
            "dataset",
            "year",
            "model_year",
            "hunt_code",
            "legacy_hunt_code_prefix",
            "hunt_code_prefix_status",
            "hunt_name",
            "residency",
            "point_level",
            "source_file",
            "source_namespace",
        ],
    )
    write_csv(SUMMARY, summary_rows, ["dataset", "summary_type", "value", "row_count"])

    status = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "crosswalk_source": str(CROSSWALK.relative_to(ROOT)),
        "crosswalk_rows_loaded": len(crosswalk),
        "target_files": [str(path.relative_to(ROOT)) for path in TARGETS],
        "row_count_preserved": all(bool(result["row_count_preserved"]) for result in results),
        "results": results,
        "detail_path": str(DETAIL.relative_to(ROOT)),
        "summary_path": str(SUMMARY.relative_to(ROOT)),
        "rule": "Preserve raw hunt_code; add legacy_hunt_code_prefix for cross-year model routing.",
    }
    STATUS.write_text(json.dumps(status, indent=2), encoding="utf-8")
    print(json.dumps(status, indent=2))


if __name__ == "__main__":
    main()
